apiVersion: apps/v1
kind: Deployment
metadata:
  name: answer-time-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: answer-time
  template:
    metadata:
      labels:
        app: answer-time
    spec:
      containers:
      - name: answer-time-app
        image: YOUR_AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/luka-exp:new-ans-time
        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: ecr-registry
