apiVersion: v1
kind: Service
metadata:
  name: ask-time-service
spec:
  type: NodePort
  selector:
    app: ask-time
  ports:
  - port: 5000          # Service 暴露的端口
    targetPort: 5000    # Pod 中的容器端口
    nodePort: 30000     # 節點暴露的端口