apiVersion: v1
clusters:
- cluster:
    server: https://YOUR_PUBLIC_IP:6443
    certificate-authority-data: YOUR_CLUSTER_CA_CRT
  name: YOUR_CLUSTER_NAME
contexts:
- context:
    cluster: YOUR_CLUSTER_NAME
    namespace: default
    user: my-cluster-admin 
  name: my-cluster-admin@YOUR_CLUSTER_NAME
current-context: my-cluster-admin@YOUR_CLUSTER_NAME
kind: Config
preferences: {}
users:
- name: my-cluster-admin
  user:
    client-certificate-data: YOUR_DEVELOPER_CRT
    client-key-data: YOUR_DEVELOPER_KEY